# Generated by Django 4.2.6 on 2023-10-28 00:43

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(related_name='customuser_set', to='auth.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiaNombre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HPCMetodosSuicida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HPCSituacionContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HPCTiposDemandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HPCTiposRespuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InfoMiembros',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('numero_hijos', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('telefono', models.CharField(null=True)),
                ('celular', models.CharField(null=True)),
                ('sisben', models.BooleanField()),
                ('nombre_eps', models.CharField(max_length=50)),
                ('contador_llamadas_psicologicas', models.IntegerField(default=0)),
                ('contador_asesorias_psicologicas', models.IntegerField(default=0)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.estadocivil')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.etnia')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPacientes',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_hijos', models.IntegerField()),
                ('direccion', models.TextField(max_length=150)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('barrio', models.CharField(max_length=100)),
                ('poblacion_vulnerable', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(null=True)),
                ('celular', models.CharField(null=True)),
                ('sisben', models.BooleanField()),
                ('nombre_eps', models.CharField(max_length=50)),
                ('cant_asesorias_psicologicas', models.IntegerField(default=0)),
                ('cant_atenciones_urgencias', models.IntegerField(default=0)),
                ('escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.escolaridad')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.estadocivil')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.etnia')),
            ],
        ),
        migrations.CreateModel(
            name='Lecto1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecto2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Razonamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegimenSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiNoNunca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PsiLlamadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_paciente', models.CharField(max_length=100, null=True)),
                ('fecha_llamada', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('motivo_llamada', models.TextField(max_length=5000, null=True)),
                ('conducta_a_seguir', models.TextField(max_length=5000, null=True)),
                ('observaciones', models.TextField(max_length=5000, null=True)),
                ('seguimiento24', models.TextField(max_length=5000, null=True)),
                ('seguimiento48', models.TextField(max_length=5000, null=True)),
                ('seguimiento72', models.TextField(max_length=5000, null=True)),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dianombre')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infomiembros')),
            ],
        ),
        migrations.CreateModel(
            name='PacientePip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_pip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pip')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_calculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.calculo')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('guardado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pertenece_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='lectoescritura_indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.lecto1'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='lectoescritura_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.lecto2'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.municipio'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ocupacion'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='razonamiento_analitico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.razonamiento'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='regimen_seguridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.regimenseguridad'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipodocumento'),
        ),
        migrations.AddField(
            model_name='infomiembros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipousuario'),
        ),
        migrations.AddField(
            model_name='infomiembros',
            name='regimen_seguridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.regimenseguridad'),
        ),
        migrations.AddField(
            model_name='infomiembros',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo'),
        ),
        migrations.AddField(
            model_name='infomiembros',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipodocumento'),
        ),
        migrations.CreateModel(
            name='HPC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asesoria', models.DateField(default=django.utils.timezone.now)),
                ('lugar', models.TextField(max_length=150)),
                ('edad_usuario_actual', models.IntegerField()),
                ('diag_trans_mental', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('diag_categoria', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('diag_por_profesional', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('tratamiento', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('medicamentos', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('adherencia', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('barreras_acceso', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('es_hasido_consumidor', models.BooleanField(default=False)),
                ('edad_inicio', models.IntegerField(default=django.db.models.deletion.SET_NULL, null=True)),
                ('periodo_ultimo_consumo', models.DateField(null=True)),
                ('conductas_sex_resgo', models.TextField(max_length=300, null=True)),
                ('intervenciones_previas', models.TextField(max_length=300, null=True)),
                ('consumo_familiar', models.BooleanField(default=False)),
                ('vinculo', models.TextField(max_length=300, null=True)),
                ('intentos_previos', models.IntegerField(default=0)),
                ('fecha_ultimo_intento', models.DateField(null=True)),
                ('manejo_hospitalario', models.BooleanField(null=True)),
                ('cedula_profesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infomiembros')),
                ('cedula_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('disponibilidad_medios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_disponibilidad_medios', to='main.sinonunca')),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpcmetodossuicida')),
                ('presencia_planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_presencia_planeacion', to='main.sinonunca')),
                ('spa_inicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hpc_spa_inicio', to='main.spa')),
                ('sustancia_impacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hpc_sustancia_impacto', to='main.spa')),
                ('tendencia_suicida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_tendencia_suicida', to='main.sinonunca')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='pertenece_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pais'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipousuario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customuser_set', to='auth.permission'),
        ),
    ]
