# Generated by Django 4.2.6 on 2023-12-31 18:58

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsiLlamadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=100, null=True)),
                ('fecha_llamada', models.DateTimeField(default=django.utils.timezone.now)),
                ('edad', models.IntegerField(null=True)),
                ('observaciones', models.TextField(max_length=5000, null=True)),
                ('seguimiento24', models.TextField(max_length=5000, null=True)),
                ('seguimiento48', models.TextField(max_length=5000, null=True)),
                ('seguimiento72', models.TextField(max_length=5000, null=True)),
            ],
            options={
                'db_table': 'main_psillamadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(related_name='customuser_set', to='auth.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConductasASeguir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiaNombre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusPersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HPC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asesoria', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.TextField(max_length=150, null=True)),
                ('edad_usuario_actual', models.IntegerField(null=True)),
                ('diag_trans_mental', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('diag_categoria', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('diag_por_profesional', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('tratamiento', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('medicamentos', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('adherencia', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('barreras_acceso', models.TextField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True)),
                ('es_hasido_consumidor', models.BooleanField(default=False)),
                ('edad_inicio', models.IntegerField(default=django.db.models.deletion.SET_NULL, null=True)),
                ('periodo_ultimo_consumo', models.DateField(null=True)),
                ('conductas_sex_riesgo', models.TextField(max_length=300, null=True)),
                ('intervenciones_previas', models.TextField(max_length=300, null=True)),
                ('consumo_familiar', models.BooleanField(default=False)),
                ('vinculo', models.TextField(max_length=300, null=True)),
                ('intentos_previos', models.IntegerField(default=0)),
                ('fecha_ultimo_intento', models.DateField(null=True)),
                ('manejo_hospitalario', models.BooleanField(null=True)),
                ('metodo', models.TextField(max_length=300, null=True)),
                ('letalidad', models.TextField(max_length=300, null=True)),
                ('signos', models.TextField(max_length=300, null=True)),
                ('acontecimientos_estresantes', models.TextField(max_length=300, null=True)),
                ('historial_familiar', models.BooleanField(default=False)),
                ('factores_protectores', models.TextField(max_length=300, null=True)),
                ('red_apoyo', models.TextField(max_length=300, null=True)),
                ('victima', models.BooleanField(default=False)),
                ('tipo_violencia', models.TextField(max_length=300, null=True)),
                ('agresor', models.TextField(max_length=300, null=True)),
                ('inst_reporte_legal', models.TextField(max_length=300, null=True)),
                ('asistencia_cita', models.BooleanField(default=False)),
                ('contacto', models.BooleanField(default=False)),
                ('contacto_interrumpido', models.BooleanField(default=False)),
                ('inicia_otro_programa', models.BooleanField(default=False)),
                ('p_tamizaje', models.TextField(max_length=300, null=True)),
                ('c_o_d', models.TextField(max_length=300, null=True)),
                ('anotaciones_antecedentes_psiquiatricos', models.TextField(max_length=5000, null=True)),
                ('anotaciones_consumoSPA', models.TextField(max_length=5000, null=True)),
                ('anotaciones_comportamiento_suic', models.TextField(max_length=5000, null=True)),
                ('anotaciones_antecedentes_violencia', models.TextField(max_length=5000, null=True)),
                ('anotaciones_libres_profesional', models.TextField(max_length=5000, null=True)),
                ('seguimiento1', models.TextField(max_length=5000, null=True)),
                ('seguimiento2', models.TextField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HPCMetodosSuicida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HPCSituacionContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HPCTiposDemandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HPCTiposRespuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPacientes',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('numero_hijos', models.IntegerField(null=True)),
                ('direccion', models.TextField(max_length=150, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('barrio', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(null=True)),
                ('sisben', models.BooleanField(null=True)),
                ('cant_asesorias_psicologicas', models.IntegerField(default=0)),
                ('cant_llamadas', models.IntegerField(default=0)),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eps')),
                ('escolaridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.escolaridad')),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.estadocivil')),
                ('etnia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etnia')),
            ],
        ),
        migrations.CreateModel(
            name='Lecto1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecto2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoblacionVulnerable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PsiMotivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Razonamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegimenSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiNoNunca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SPAActuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.infopacientes')),
                ('id_sustancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spa')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCTiposRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpc')),
                ('id_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpctiposrespuestas')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCTiposDemandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpc')),
                ('id_tipo_demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpctiposdemandas')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCSituacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpc')),
                ('id_situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpcsituacioncontacto')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCConductasASeguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpc')),
                ('id_conducta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conductasaseguir')),
            ],
        ),
        migrations.CreateModel(
            name='PsiLlamadasMotivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psillamadas')),
                ('id_motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpcsituacioncontacto')),
            ],
        ),
        migrations.CreateModel(
            name='PsiLlamadasConductas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conducta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conductasaseguir')),
                ('id_llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psillamadas')),
            ],
        ),
        migrations.CreateModel(
            name='PacientePip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_pip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pip')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_calculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.calculo')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('guardado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pertenece_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='lectoescritura_indicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecto1'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='lectoescritura_nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecto2'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.municipio'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='ocupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ocupacion'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='poblacion_vulnerable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.poblacionvulnerable'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='razonamiento_analitico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.razonamiento'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='regimen_seguridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.regimenseguridad'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sexo'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='cedula_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='disponibilidad_medios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_disponibilidad_medios', to='main.sinonunca'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='estatus_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.estatuspersona'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='presencia_planeacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_presencia_planeacion', to='main.sinonunca'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='spa_inicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hpc_spa_inicio', to='main.spa'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='sustancia_impacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hpc_sustancia_impacto', to='main.spa'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='tendencia_suicida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_tendencia_suicida', to='main.sinonunca'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='tratamiento_psiquiatrico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hpc_tratamiento_psiquiatrico', to='main.sinonunca'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pertenece_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pais'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipousuario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customuser_set', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='InfoMiembros',
            fields=[
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_hijos', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('celular', models.CharField(null=True)),
                ('sisben', models.BooleanField(default=False, null=True)),
                ('contador_llamadas_psicologicas', models.IntegerField(default=0)),
                ('contador_asesorias_psicologicas', models.IntegerField(default=0)),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eps')),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.estadocivil')),
                ('etnia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.etnia')),
                ('regimen_seguridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.regimenseguridad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='hpc',
            name='id_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infomiembros'),
        ),
    ]
