# Generated by Django 4.2.6 on 2023-12-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hpc',
            name='sexo_usuario',
        ),
    ]
