# Generated by Django 4.2.6 on 2023-10-28 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusPersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hpc',
            name='agresor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpc',
            name='anotaciones_antecedentes_psiquiatricos',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='anotaciones_antecedentes_violencia',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='anotaciones_comportamiento_suic',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='anotaciones_consumoPSA',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='anotaciones_libres_profesional',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='asistencia_cita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpc',
            name='c_o_d',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='cond_a_seguir',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='contacto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpc',
            name='contacto_interrumpido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpc',
            name='historial_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpc',
            name='inicia_otro_programa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpc',
            name='inst_reporte_legal',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='letalidad',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='p_tamizaje',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='red_apoyo',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='signos',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='tratamiento_psiquiatrico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hpc_tratamiento_psiquiatrico', to='main.sinonunca'),
        ),
        migrations.AddField(
            model_name='hpc',
            name='victima',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SPAActuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_sustancia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.spa')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCTiposRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpc')),
                ('id_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpctiposrespuestas')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCTiposDemandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpc')),
                ('id_tipo_demanda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpctiposdemandas')),
            ],
        ),
        migrations.CreateModel(
            name='RHPCSituacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpc')),
                ('id_situacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hpcsituacioncontacto')),
            ],
        ),
        migrations.AddField(
            model_name='hpc',
            name='estatus_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.estatuspersona'),
        ),
    ]
