# Generated by Django 4.2.6 on 2023-10-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_jefe',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_trabajador',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipousuario'),
        ),
    ]
