# Generated by Django 4.2.6 on 2023-11-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_estatuspersona_hpc_agresor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomiembros',
            name='email',
        ),
        migrations.RemoveField(
            model_name='infomiembros',
            name='nombre',
        ),
    ]
