# Generated by Django 4.2.6 on 2023-10-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tipousuario_remove_customuser_is_jefe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
