# Generated by Django 4.2.6 on 2024-01-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cedula_usuario_psillamadas_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpc',
            name='dia_semana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dianombre'),
        ),
    ]
