# Generated by Django 4.2.6 on 2023-11-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_infomiembros_email_remove_infomiembros_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomiembros',
            name='sisben',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
