# Generated by Django 4.2.6 on 2023-11-02 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_infomiembros_sisben'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomiembros',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.estadocivil'),
        ),
        migrations.AlterField(
            model_name='infomiembros',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.etnia'),
        ),
        migrations.AlterField(
            model_name='infomiembros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infomiembros',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipodocumento'),
        ),
    ]
