# Generated by Django 4.2.6 on 2024-06-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hpc_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psillamadas',
            name='id_psicologo',
        ),
    ]
