# Generated by Django 4.2.6 on 2023-10-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_escolaridad_estadocivil_etnia_lecto1_lecto2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPacientes',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_hijos', models.IntegerField()),
                ('direccion', models.TextField(max_length=150)),
                ('barrio', models.CharField(max_length=100)),
                ('telefono', models.CharField(null=True)),
                ('celular', models.CharField(null=True)),
                ('sisben', models.BooleanField()),
                ('nombre_eps', models.CharField(max_length=50)),
                ('cant_asesorias_psicologicas', models.IntegerField(default=0)),
                ('cant_atenciones_urgencias', models.IntegerField(default=0)),
                ('escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.escolaridad')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.estadocivil')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.etnia')),
                ('lectoescritura_indicador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.lecto1')),
                ('lectoescritura_nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.lecto2')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ocupacion')),
                ('razonamiento_analitico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.razonamiento')),
                ('regimen_seguridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.regimenseguridad')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PacientePip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_pip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pip')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infopacientes')),
                ('id_calculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.calculo')),
            ],
        ),
    ]
