# Generated by Django 4.2.6 on 2024-06-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_psillamadas_id_psicologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='psillamadas',
            name='id_psicologo',
            field=models.ForeignKey(db_column='id_psicologo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.infomiembros'),
        ),
    ]
