# Generated by Django 4.2.6 on 2023-11-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_infomiembros_regimen_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomiembros',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo'),
        ),
    ]
