# Generated by Django 4.2.6 on 2023-10-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_calculo_infopacientes_pip_pacientepip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMiembros',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('numero_hijos', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('telefono', models.CharField(null=True)),
                ('celular', models.CharField(null=True)),
                ('sisben', models.BooleanField()),
                ('nombre_eps', models.CharField(max_length=50)),
                ('contador_llamadas_psicologicas', models.IntegerField(default=0)),
                ('contador_asesorias_psicologicas', models.IntegerField(default=0)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.estadocivil')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.etnia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipousuario')),
                ('regimen_seguridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.regimenseguridad')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipodocumento')),
            ],
        ),
    ]
