# Generated by Django 4.2.6 on 2023-10-27 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_infomiembros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiaNombre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('guardado_por', models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pertenece_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PsiLlamadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(default=django.db.models.deletion.SET_NULL, max_length=30)),
                ('nombre_paciente', models.CharField(max_length=100, null=True)),
                ('fecha_llamada', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('edad', models.IntegerField(default=django.db.models.deletion.SET_NULL, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=30, null=True)),
                ('poblacion_vulnerable', models.CharField(max_length=100, null=True)),
                ('motivo_llamada', models.TextField(max_length=5000, null=True)),
                ('conducta_a_seguir', models.TextField(max_length=5000, null=True)),
                ('observaciones', models.TextField(max_length=5000, null=True)),
                ('seguimiento24', models.TextField(max_length=5000, null=True)),
                ('seguimiento48', models.TextField(max_length=5000, null=True)),
                ('seguimiento72', models.TextField(max_length=5000, null=True)),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.dianombre')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infomiembros')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.municipio')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sexo')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='pertenece_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pais'),
        ),
    ]
