# Generated by Django 4.2.6 on 2023-11-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_infomiembros_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
