# Generated by Django 4.2.6 on 2023-10-27 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_departamento_dianombre_municipio_pais_psillamadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPCSituacionContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HPCTiposDemandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HPCTiposRespuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='poblacion_vulnerable',
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='sexo',
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.municipio'),
        ),
        migrations.AddField(
            model_name='infopacientes',
            name='poblacion_vulnerable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='guardado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='psillamadas',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dianombre'),
        ),
        migrations.AlterField(
            model_name='psillamadas',
            name='documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
