# Generated by Django 4.2.6 on 2023-11-02 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomiembros',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='infomiembros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
