# Generated by Django 4.2.6 on 2023-11-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_infomiembros_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomiembros',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='infopacientes',
            name='telefono',
        ),
    ]
