# Generated by Django 4.2.6 on 2023-11-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_conductasaseguir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psillamadas',
            name='conducta_a_seguir',
        ),
        migrations.CreateModel(
            name='PsiLlamadasConductas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conducta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conductasaseguir')),
                ('id_llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psillamadas')),
            ],
        ),
    ]
