# Generated by Django 4.2.6 on 2023-11-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_psillamadas_conducta_a_seguir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsiMotivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='psillamadas',
            name='motivo_llamada',
        ),
        migrations.CreateModel(
            name='PsiLlamadasMotivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psillamadas')),
                ('id_motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psimotivos')),
            ],
        ),
    ]
