# Generated by Django 4.2.6 on 2023-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_psimotivos_remove_psillamadas_motivo_llamada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
