# Generated by Django 4.2.6 on 2023-11-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoblacionVulnerable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='poblacion_vulnerable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.poblacionvulnerable'),
        ),
    ]
