# Generated by Django 4.2.6 on 2023-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_poblacionvulnerable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianombre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
