# Generated by Django 4.2.6 on 2023-11-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_dianombre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='psillamadas',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psillamadas',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sexo'),
        ),
    ]
