# Generated by Django 4.2.6 on 2023-11-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_psillamadas_edad_psillamadas_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopacientes',
            name='nombre_eps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eps'),
        ),
    ]
