# Generated by Django 4.2.6 on 2023-11-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_infopacientes_nombre_eps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infopacientes',
            old_name='cant_atenciones_urgencias',
            new_name='cant_llamadas',
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='barrio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='direccion',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='escolaridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.escolaridad'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.estadocivil'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etnia'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='lectoescritura_indicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecto1'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='lectoescritura_nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecto2'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.municipio'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='numero_hijos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='ocupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ocupacion'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='razonamiento_analitico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.razonamiento'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='regimen_seguridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.regimenseguridad'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sexo'),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='sisben',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='infopacientes',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
    ]
