# Generated by Django 4.2.6 on 2023-11-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_cant_atenciones_urgencias_infopacientes_cant_llamadas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infopacientes',
            old_name='nombre_eps',
            new_name='eps',
        ),
    ]
