# Generated by Django 4.2.6 on 2023-11-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_nombre_eps_infopacientes_eps'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpc',
            name='acontecimientos_estresantes',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='factores_protectores',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hpc',
            name='tipo_violencia',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hpc',
            name='agresor',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hpc',
            name='cond_a_seguir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.conductasaseguir'),
        ),
    ]
