# Generated by Django 4.2.6 on 2023-11-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_cedula_profesional_hpc_id_profesional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hpc',
            old_name='conductas_sex_resgo',
            new_name='conductas_sex_riesgo',
        ),
    ]
