# Generated by Django 4.2.6 on 2023-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_hpc_seguimiento1_hpc_seguimiento2_alter_hpc_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpc',
            name='edad_usuario_actual',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hpc',
            name='lugar',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
