# Generated by Django 4.2.6 on 2023-12-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_hpc_edad_usuario_actual_alter_hpc_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hpc',
            old_name='anotaciones_consumoPSA',
            new_name='anotaciones_consumoSPA',
        ),
    ]
