# Generated by Django 4.2.6 on 2023-12-06 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_anotaciones_consumopsa_hpc_anotaciones_consumospa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpc',
            name='fecha_asesoria',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
