# Generated by Django 4.2.6 on 2023-12-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_hpc_fecha_asesoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomiembros',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
