# Generated by Django 4.2.6 on 2023-12-06 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_rhpcconductasaseguir_id_asesoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomiembros',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
