# Generated by Django 4.2.6 on 2023-12-07 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_infomiembros_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psillamadas',
            name='hora',
        ),
        migrations.AlterField(
            model_name='psillamadas',
            name='fecha_llamada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
