# Generated by Django 4.2.6 on 2023-12-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_psillamadas_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomiembros',
            name='nombre_eps',
        ),
        migrations.AddField(
            model_name='infomiembros',
            name='eps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eps'),
        ),
        migrations.AlterField(
            model_name='psillamadasmotivos',
            name='id_motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hpcsituacioncontacto'),
        ),
    ]
