# Generated by Django 4.2.6 on 2023-12-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_psillamadas_id_psicologo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psillamadas',
            options={'managed': False},
        ),
    ]
