# Generated by Django 4.2.6 on 2023-12-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_psillamadas_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='psillamadas',
            table='main_psillamadas',
        ),
    ]
