# Generated by Django 4.2.6 on 2023-12-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_hpc_sexo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpc',
            name='sexo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sexo'),
        ),
    ]
